name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # use the latest version of ubuntu

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v3 #v3, node12 will be deprecated soon
      with:
        python-version: 3.9  #just upgrading from the alpine 3.6 version

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt #install the requirements

    - name: Build and Deploy
      run: |
        python render.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: _site
        path: _site/

    - name: Push artifacts back to the original repository
      uses: stefanzweifel/git-auto-commit-action@v5
