name: Build MPNK Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # use the latest version of ubuntu
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v3 #v3, node12 will be deprecated soon
      with:
        python-version: 3.9  #just upgrading from the alpine 3.6 version

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt #install the requirements

    - name: Build and Deploy
      run: |
        python render.py

    - uses: actions/upload-artifact@master
      with:
        name: site-package
        path: _site
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@master
      with:
        name: site-package
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main